"""Compress the embedded dashboard before C++ compilation.

web/ contains the editable HTML, CSS and JavaScript. This pre-build step emits a
small byte array so the full dashboard costs roughly one quarter as much flash.
The gzip timestamp is fixed, keeping firmware builds reproducible.
"""

from pathlib import Path
import gzip
import os
import re
import shutil
import subprocess
import tempfile

try:
    Import("env")  # supplied by PlatformIO/SCons
    project = Path(env.subst("$PROJECT_DIR"))
except NameError:
    project = Path(__file__).resolve().parent.parent
output_path = project / "src" / "web_assets_gzip.h"
html = (project / "web/index.html").read_text(encoding="utf-8")
for name in ("dashboard.css", "dashboard.js", "product.css", "product.js"):
    marker = "/* @include " + name + " */"
    if marker in html:
        html = html.replace(marker, (project / "web" / name).read_text(encoding="utf-8"))
icon = (project / "web/favicon.svg").read_text(encoding="utf-8")

# The dashboard is one enormous minified line, so a broken string literal is
# invisible on inspection and takes the whole <script> down with it -- the page
# renders, nothing works, and the browser says only "Unexpected token". Check it
# here, where the failure is a build error instead of a bricked dashboard.
def check_script(source: str) -> None:
    scripts = re.findall(r"<script>(.*?)</script>", source, re.DOTALL)
    if not scripts:
        return
    node = shutil.which("node")
    if node is None:
        print("embed_web: node not found, skipping dashboard JS syntax check")
        return
    with tempfile.NamedTemporaryFile("w", suffix=".js", encoding="utf-8",
                                     delete=False, newline="") as handle:
        handle.write("\n".join(scripts))
        temp = handle.name
    try:
        result = subprocess.run([node, "--check", temp], capture_output=True,
                                text=True)
    finally:
        os.unlink(temp)
    if result.returncode != 0:
        raise RuntimeError("dashboard JavaScript does not parse:\n"
                           + (result.stderr or result.stdout))

check_script(html)

payload = gzip.compress(html.encode("utf-8"), compresslevel=9, mtime=0)
rows = []
for offset in range(0, len(payload), 16):
    rows.append("  " + ", ".join(f"0x{byte:02x}" for byte in payload[offset:offset + 16]))

generated = """// Generated by scripts/embed_web.py; edit web/ instead.\n#pragma once\n#include <Arduino.h>\n\n"""
generated += 'static const char DASHBOARD_ICON[] PROGMEM = R"ICON(' + icon + ')ICON";\n\n'
generated += "static const uint8_t DASHBOARD_GZIP[] PROGMEM = {\n"
generated += ",\n".join(rows)
generated += "\n};\nstatic const size_t DASHBOARD_GZIP_LEN = sizeof(DASHBOARD_GZIP);\n"

if not output_path.exists() or output_path.read_text(encoding="utf-8") != generated:
    output_path.write_text(generated, encoding="utf-8", newline="\n")
